DATASET:
  NAME: "CIFAR10"

INPUT:
  BASE_CONFIDENCE_BOUND: 0.9
  NEW_CONFIDENCE_BOUND: 0.9
  CONFIDENCE_BOUND: 0.9

TRAIN:
  WARMUP: 20
  TRITRAINING_EPOCH: 10

# 10 2 base: 92.71, new: 93.57, all: 84.28
# 20 10 base: 93.65, new: 94.73, all: 85.20