DATASET:
  NAME: "DescribableTextures"

INPUT:
  BASE_CONFIDENCE_BOUND: 0.9
  NEW_CONFIDENCE_BOUND: 0.9

TRAINER:
  PROMPTSRC:
    GPA_MEAN: 30
    GPA_STD: 30

TRAIN:
  WARMUP: 5
  TRITRAINING_EPOCH: 22