DATASET:
  NAME: "DescribableTextures"

INPUT:
  BASE_CONFIDENCE_BOUND: 0.9
  NEW_CONFIDENCE_BOUND: 0.9
  
TRAIN:
  WARMUP: 15
  TRITRAINING_EPOCH: 5

TRAINER:
  PROMPTSRC:
    GPA_MEAN: 30
    GPA_STD: 30
