DATASET:
  NAME: "FGVCAircraft"

INPUT:
  BASE_CONFIDENCE_BOUND: 0.8
  NEW_CONFIDENCE_BOUND: 0.8

TRAIN:
  WARMUP: 50
  TRITRAINING_EPOCH: 10

# 25 + 5
# 30 + 5
# 40 + 5
# 50 + 1
# 50 + 5 # 40.80, 23.38, 29.60