DATASET:
  NAME: "Food101"

INPUT:
  BASE_CONFIDENCE_BOUND: 0.99
  NEW_CONFIDENCE_BOUND: 0.9

TRAIN:
  WARMUP: 5
  TRITRAINING_EPOCH: 20

TRAINER:
  PROMPTSRC:
    GPA_MEAN: 15
    GPA_STD: 1

# 15 90.50
# 20 90.39