DATASET:
  NAME: "OxfordPets"

INPUT:
  BASE_CONFIDENCE_BOUND: 0.99
  NEW_CONFIDENCE_BOUND: 0.9

TRAIN:
  WARMUP: 15 # best 10
  TRITRAINING_EPOCH: 2

TRAINER:
  PROMPTSRC:
    GPA_MEAN: 30
    GPA_STD: 30