DATASET:
  NAME: "OxfordPets"

INPUT:
  BASE_CONFIDENCE_BOUND: 0.99
  NEW_CONFIDENCE_BOUND: 0.9

TRAIN:
  WARMUP: 20 # best 10 
  TRITRAINING_EPOCH: 5

TRAINER:
  PROMPTSRC:
    GPA_MEAN: 30
    GPA_STD: 30 

# 正常tritrain new
# 15 95.92 96.07
# 10 96.15 95.90
# 13 95.87
# 20 95.98 96.30
# 18 -- 96.09